spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  sql:
    init:
      mode: never
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:}
    password: ${MYSQL_PASSWORD:}
    url: jdbc:mysql://${MYSQL_HOST:}:${MYSQL_PORT:}/productions?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

server:
  port: 8081

#  jwt:
#    secret: WSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8I
#    expiration: 60000


