INSERT INTO `productions` (id, name, description, genre, image_url, length, production_type, rating, rent_price, video_url, year)
VALUES (1, 'Alien: Romulus', 'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.', 'HORROR', 'https://wiziwiz.com/wp-content/uploads/2024/06/wiziwiz-alien-romulus-poster-.jpg', '132', 'MOVIE', '5', '10', 'x0XDEhP4MQs', '2024'),
       (2, 'Stalker', 'Stalker IPA: is a 1979 Soviet science fiction film ', 'ADVENTURE', 'https://www.sensesofcinema.com/wp-content/uploads/2014/02/stalker-640x400.jpg', '184', 'MOVIE', '5', '4', 'YuOnfQd-aTw', '1979'),
       (3, 'Forrest Gump', 'The film follows the life of an Alabama man', 'DRAMA', 'https://m.media-amazon.com/images/I/91++WV6FP4L._AC_UF894,1000_QL80_.jpg', '142', 'MOVIE', '5', '8', 'bLvqoHBptjg', '1994'),
       (4, 'Fight Club', 'Fight Club is a 1999 American film directed by David Fincher', 'DRAMA', 'https://m.media-amazon.com/images/M/MV5BMjk3NTYyMzc4Nl5BMl5BanBnXkFtZTcwODU3ODMzMw@@._V1_.jpg', '139', 'MOVIE', '5', '6', 'qtRKdVHc-cE', '1999'),
       (5, 'Gladiator', 'Crowe portrays the Roman general Maximus Decimus Meridius', 'ACTION', 'https://m.media-amazon.com/images/I/51GA6V6VE1L._AC_UF894,1000_QL80_.jpg', '153', 'MOVIE', '5', '4', 'P5ieIbInFpg', '2000'),
       (6, 'Oppenheimer', 'Oppenheimer is a 2023 epic biographical thriller drama film', 'HISTORICAL', 'https://images.indianexpress.com/2023/05/nolan-movie.jpg', '180', 'MOVIE', '5', '9', 'bK6ldnjE3Y0', '2023'),
       (7, 'Friends', 'Friends is an American television sitcom created by David Crane and Marta Kauffman', 'COMEDY', 'https://uniathenaprods3.uniathena.com/s3fs-public/insights-article/seriesreview-e2-80-9cfriends-e2-80-9d_0.jpg', '30', 'TV', '5', '10', 'IEEbUzffzrk&t=2s', '1994'),
       (8, 'Breaking Bad', 'Breaking Bad is an American crime drama television series created and produced', 'ADVENTURE', 'https://ntvb.tmsimg.com/assets/p8696131_b_h10_aa.jpg?w=960&h=540', '45', 'TV', '4', '8', 'HhesaQXLuRY', '2008'),
       (9, 'Game of Thrones', 'Game of Thrones is an American fantasy drama television series created by ', 'FANTASY', 'https://assets-prd.ignimgs.com/2022/01/14/gameofthrones-allseasons-sq-1642120207458.jpg', '60', 'TV', '5', '7', 'bjqEWgDVPe0', '2011'),
       (10, 'The Office', 'The Office is an American mockumentary sitcom television series based on the 2001–2003 BBC ', 'COMEDY', 'https://ntvb.tmsimg.com/assets/p7893514_b_h8_ab.jpg?w=960&h=540', '22', 'TV', '3', '5', 'tNcDHWpselE', '2005'),
       (11, 'Black Mirror', 'Black Mirror is a British anthology television series created by Charlie Brooker. The series ', 'THRILLER', 'https://images.justwatch.com/poster/307079555/s332/season-6', '60', 'TV', '4', '9', 'V0XOApF5nLU', '2011'),
       (12, 'House', 'House (also called House, M.D.) is an American medical drama television series that originally', 'DRAMA', 'https://pics.filmaffinity.com/house_m_d-469252061-large.jpg', '45', 'TV', '5', '3', 'MczMB8nU1sY', '2004');